[package]
name = "cell_monitor"
version = "0.1.0"
edition = "2024"

[dependencies]
udev = "0.9.3"

[dev-dependencies]
cargo-deny = "0.18.5"
cargo-tarpaulin = "0.34.1"
cargo-watch = "8.5.3"
clippy = "0.0.302"
rustfmt = "0.10.0"
